---
name: "schema"
version: "0.16.4"
usage: "generate jsonschemas for your helm charts"
description: "generate jsonschemas for your helm charts"
command: "$HELM_PLUGIN_DIR/bin/helm-schema"
hooks:
  install: "$HELM_PLUGIN_DIR/install-binary.sh"
  update: "$HELM_PLUGIN_DIR/install-binary.sh -u"
